### ISSUE TITLE
failed to boot from SATA disk on espressobin

### ISSUE THREAD

**Issue by hardlyhack** [uboslinux/ubos-devices#1]
Hi,

I am following this instruction from https://ubos.net/docs/users/installation/espressobin.html

But when I was trying to boot from SATA disk, it seems to try to mount /dev/sda2, which is swap partition. 

I manually edited bootargs in uEnv-sata.txt to boot from /dev/sda3, and that seemed to resolve the issue.

I'm opening this issue as I am not sure what the correct way to fix this myself.

**Comment by jernst** [comment]
This is actually a known issue, see https://github.com/uboslinux/ubos-admin/issues/402 and release notes at the bottom: https://ubos.net/docs/releases/beta13/release-notes/index.html.

Code has been written to fix this; should be in the next release.
